{{- if .Values.persistence.enabled }}
{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mealie.fullname" . }}-data
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
{{- if and .Values.persistence.backup.enabled (not .Values.persistence.backup.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mealie.fullname" . }}-backup
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - {{ .Values.persistence.backup.accessMode }}
  {{- if .Values.persistence.backup.storageClass }}
  storageClassName: {{ .Values.persistence.backup.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backup.size | quote }}
{{- end }}
{{- end }}
